"""add listings table

Revision ID: fd5df7bd8644
Revises: 0009_merge_heads
Create Date: 2026-04-03 04:12:54.362375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5df7bd8644'
down_revision: Union[str, None] = "0009_merge_heads"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deal_type', sa.Enum('RENT', 'SALE', 'MORTGAGE', name='dealtype', native_enum=False, length=32), nullable=False),
    sa.Column('visibility', sa.Enum('NETWORK', 'PUBLIC', name='listingvisibility', native_enum=False, length=32), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('location_summary', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready_to_publish', 'published', 'archived', name='listingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('inventory_file_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_owner_id'), 'listings', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_owner_id'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
