events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://people:3000;
    }

    location /advisor {
      proxy_pass http://advisor:3001;
    }

    location /ops {
      proxy_pass http://ops:3002;
    }

    location /api/auth {
      proxy_pass http://auth:9001;
    }

    location /api/contracts {
      proxy_pass http://contract:9002;
    }

    location /api/signatures {
      proxy_pass http://signature:9003;
    }

    location /api/advisor {
      proxy_pass http://advisor-service:9010;
    }
  }
}
