"""Contract domain enums — ported from clone PRContract domain."""
from __future__ import annotations

from enum import Enum


class ContractType(str, Enum):
    PROPERTY_RENT = "PROPERTY_RENT"
    BUYING_AND_SELLING = "BUYING_AND_SELLING"


class PartyType(str, Enum):
    LANDLORD = "LANDLORD"
    TENANT = "TENANT"


class ContractStatus(str, Enum):
    ADMIN_STARTED = "ADMIN_STARTED"
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PENDING_COMMISSION = "PENDING_COMMISSION"
    EDIT_REQUESTED = "EDIT_REQUESTED"
    PARTY_REJECTED = "PARTY_REJECTED"
    PENDING_ADMIN_APPROVAL = "PENDING_ADMIN_APPROVAL"
    ADMIN_REJECTED = "ADMIN_REJECTED"
    COMPLETED = "COMPLETED"
    REVOKED = "REVOKED"
    PDF_GENERATED = "PDF_GENERATED"
    PDF_GENERATING_FAILED = "PDF_GENERATING_FAILED"


class PRContractStep(str, Enum):
    # Common steps
    DATES_AND_PENALTIES = "DATES_AND_PENALTIES"
    MONTHLY_RENT = "MONTHLY_RENT"
    RENT_PAYMENT = "RENT_PAYMENT"
    DEPOSIT = "DEPOSIT"
    ADD_COUNTER_PARTY = "ADD_COUNTER_PARTY"
    DEPOSIT_PAYMENT = "DEPOSIT_PAYMENT"
    # Tenant steps
    TENANT_INFORMATION = "TENANT_INFORMATION"
    TENANT_APPROVE = "TENANT_APPROVE"
    TENANT_SIGNATURE = "TENANT_SIGNATURE"
    TENANT_COMMISSION = "TENANT_COMMISSION"
    TENANT_REJECTED = "TENANT_REJECTED"
    TENANT_EDIT_REQUEST = "TENANT_EDIT_REQUEST"
    # Landlord steps
    LANDLORD_INFORMATION = "LANDLORD_INFORMATION"
    PROPERTY_SPECIFICATIONS = "PROPERTY_SPECIFICATIONS"
    PROPERTY_DETAILS = "PROPERTY_DETAILS"
    PROPERTY_FACILITIES = "PROPERTY_FACILITIES"
    LANDLORD_SIGNATURE = "LANDLORD_SIGNATURE"
    LANDLORD_COMMISSION = "LANDLORD_COMMISSION"
    LANDLORD_REJECTED = "LANDLORD_REJECTED"
    LANDLORD_EDIT_REQUEST = "LANDLORD_EDIT_REQUEST"
    # Admin steps
    ADMIN_APPROVE = "ADMIN_APPROVE"
    ADMIN_REJECT = "ADMIN_REJECT"
    # Tracking code
    TRACKING_CODE_REQUESTED = "TRACKING_CODE_REQUESTED"
    TRACKING_CODE_DELIVERED = "TRACKING_CODE_DELIVERED"
    TRACKING_CODE_FAILED = "TRACKING_CODE_FAILED"
    # Wizard-specific (our additions)
    PLACE_INFORMATION = "PLACE_INFORMATION"
    DATING = "DATING"
    MORTGAGE = "MORTGAGE"
    RENTING = "RENTING"
    SALE_PRICE = "SALE_PRICE"
    SIGNING = "SIGNING"
    WITNESS = "WITNESS"
    FINISH = "FINISH"


class PRContractState(str, Enum):
    DRAFT = "DRAFT"
    TENANT_REJECTED = "TENANT_REJECTED"
    TENANT_EDIT_REQUEST = "TENANT_EDIT_REQUEST"
    LANDLORD_REJECTED = "LANDLORD_REJECTED"
    LANDLORD_EDIT_REQUEST = "LANDLORD_EDIT_REQUEST"
    ADMIN_REJECTED = "ADMIN_REJECTED"
    PENDING_TENANT_APPROVAL = "PENDING_TENANT_APPROVAL"
    PENDING_TENANT_INFORMATION = "PENDING_TENANT_INFORMATION"
    PENDING_LANDLORD_INFORMATION = "PENDING_LANDLORD_INFORMATION"
    PENDING_LANDLORD_SIGNATURE = "PENDING_LANDLORD_SIGNATURE"
    PENDING_TENANT_SIGNATURE = "PENDING_TENANT_SIGNATURE"
    PENDING_PAYING_COMMISSION = "PENDING_PAYING_COMMISSION"
    PENDING_LANDLORD_COMMISSION = "PENDING_LANDLORD_COMMISSION"
    PENDING_TENANT_COMMISSION = "PENDING_TENANT_COMMISSION"
    PENDING_ADMIN_APPROVAL = "PENDING_ADMIN_APPROVAL"
    PENDING_TRACKING_CODE_REQUEST = "PENDING_TRACKING_CODE"
    PENDING_TRACKING_CODE_DELIVERY = "PENDING_TRACKING_CODE_DELIVERY"
    TRACKING_CODE_DELIVERED = "TRACKING_CODE_DELIVERED"
    PDF_GENERATED = "PDF_GENERATED"


class PaymentMethod(str, Enum):
    CASH = "CASH"
    CHEQUE = "CHEQUE"
    TRANSFER = "TRANSFER"


class PaymentStatus(str, Enum):
    PAID = "PAID"
    UNPAID = "UNPAID"
    OVERDUE = "OVERDUE"
    CANCELLED = "CANCELLED"
    PAYER_CLAIMED = "PAYER_CLAIMED_TO_HAVE_PAID"
    PAYEE_CONFIRMED = "PAYEE_CONFIRMED_RECEIPT"
    PAYEE_DENIED = "PAYEE_DENIED_RECEIPT"


class TrackingCodeStatus(str, Enum):
    NOT_GENERATED = "NOT_GENERATED"
    REQUESTED = "REQUESTED"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"


class ProvinceType(str, Enum):
    TEHRAN = "TEHRAN"
    OTHERS = "OTHERS"


class InvoiceStatus(str, Enum):
    PAID = "PAID"
    NOT_PAID = "NOT_PAID"


class TransactionStatus(str, Enum):
    SUCCESS = "SUCCESS"
    PENDING = "PENDING"
    FAILED = "FAILED"


class WalletTransactionCategory(str, Enum):
    RENT = "RENT"
    DEPOSIT = "DEPOSIT"
    COMMISSION = "COMMISSION"
    WALLET_CHARGE = "WALLET_CHARGE"
    CUSTOM_PAYMENT = "CUSTOM_PAYMENT"
    MANUAL_CHARGE = "MANUAL_CHARGE"
    WALLET_WITHDRAW = "WALLET_WITHDRAW"
    REFUND = "REFUND"
