apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amline-platform
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/upstream-keepalive-connections: "512"
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/limit-connections: "50"
spec:
  ingressClassName: nginx
  rules:
    - host: amline.ir
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: amline-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amline-web
                port:
                  number: 3000
