apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: amline-api
spec:
  minAvailable: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: amline-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: amline-web
spec:
  minAvailable: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: amline-web
